### ISSUE TITLE
Support for Mod Foods

### ISSUE THREAD

**Issue by NarwhalAndMe** [TheRedBrain/food-overhaul#1]
Is it possible for you to add support for mod food by generating stats for food through the saturation values? It would require tuning of the algorithm used to create the values in order to maintain balance, but it would fix the problem of having to customize every single vanilla food within the mod itself, and also create support for mods which change the saturation values of vanilla food as well.

**Comment by TheRedBrain** [comment]
Hi!

I would love to add support for mod food!

But since I use a unique status effect for each food item, it's not really possible (in a realistic amount of time) to add that kind of support. That will hopefully change when status effects become data-driven. which I expect to happen in the 1.21.x update cycle.

Data-driven status effects would allow to relatively easily add mod support using data packs and would also allow simple customization of existing effects.

I don't know how to even begin designing an algorithm that determines an interesting food effect only based on existing saturation values. The whole point of this overhaul is to create interesting and diverse food and that requires manual balancing imo.

**Comment by Personaless** [comment]
I know Spice of Life: Valheim edition does something similar, but supports adding foods via the config. Not sure how different the implementation for the effects are between the two, but I hope it might be useful for you.

**Comment by TheRedBrain** [comment]
SoL:Valheim does indeed have support for mod food. However they only provide a boost to max health. A algorithm for converting existing saturation values to a boost to a single attribute can be balanced in a reasonable amount of time.

SoL:Valheim definitely improves the food situation, but there is still a combination of X food items (X being the number of food slots) that will always be the best for every player.

The goal for Food Overhaul is to give players choices.
If you are a mage character, you want to prioritise food that increases your max mana.
As a melee fighter you want max health. Or more stamina.

This can be expanded upon. Maybe some food gives resistances to some damage types.
E.g. you are planning a trip into a fire themed dungeon. Eating food that increases fire resistance might be a better choice than more health.

Food Overhaul might not be a good choice if you want to just plug'n'play, but it was not designed for that. If you want to create a mod pack or server with meaningful gameplay (and invest some time to set it up via add-ons or with the upcoming data-driven status effects), Food Overhaul has the potential to make food an interesting part of the gameplay.

**Comment by Luther-Gray** [comment]
Coming back to this for 1.21.1. Any word on Modded support? Even if it's just a fallback where you get X effect for Y food tag?

I'm trying to weave this into my modpack, however it has too many dependencies for me to justify putting in without modded food support (I would already need to disable a lot of stuff from the other mods. Adding on the modded foods in addition sounds like too much work. I'd basically be remaking the mod at that point).

If it didn't require Stamina Attributes, Health Overhaul, and all the others then I would feel more confident about slapping it in and hooking up the compatibility I needed myself.

**Comment by TheRedBrain** [comment]
Hi!

In it's current form, at this point in time, supporting this mod is really difficult.
I have an idea how it could be improved, however.

I will split this mod into two parts.
The first will be the Food Overhaul itself, including a custom item component, the max_food_effects entity attribute and other backend stuff

The second part would be a library of status effects. This part would depend on all the attribute providing mods.

The two parts are then tied together by a third party mod that allows customizing default item components.
https://modrinth.com/mod/item-components and https://modrinth.com/mod/default-components are such mods.

This allows for modded foods to be easily configured to work with Overhauled Food.
And it would also move the huge amount of dependencies to the optional effect library.

Would this solve your problem?

**Comment by Luther-Gray** [comment]
Just got done reading through them. They look solid enough to me! The item components mod looks especially flexible so if the third party mod you choose was something close, I'd be able to use it for even more than Food Overhaul.

I'll definitely be coming back to add your Part 2 suite in an RPG pack eventually but splitting like this sounds like a good idea.

**Comment by TheRedBrain** [comment]
Yeah the third party mod is a temporary solution. And also I don't have to choose one, they will both work

Eventually the item components will be modify-able via data packs (a vanilla Minecraft thing) but we aren't there just yet

**Comment by TheRedBrain** [comment]
so that idea is now implemented and released 

the part two mod with the effects will be released soon

**Comment by Luther-Gray** [comment]
So fast! Appreciate that brother!

**Comment by TheRedBrain** [comment]
I basically had the idea how to deal with this while reading your first message

I got excited and just did it 😅 🤣
