### ISSUE TITLE
Add Tooltip Information

### ISSUE THREAD

**Issue by Neohedron512** [TheRedBrain/food-overhaul#2]
I suspect the answer is not right now, given how the mod works and how the attributes are applied as status effects instead of being attributes in the items themselves, but if Foods could display their applied effects when consumed, it would go a long way to making this mod more accessible.

Ideally something like the below, or akin to those resourcepacks/datapacks that show hunger and saturation stats on each food item.
![image](https://github.com/user-attachments/assets/b4e42fd6-4c67-4968-b9e5-b1eb068e2d1d)

Thank you for the great mod, Have a good day.

**Comment by TheRedBrain** [comment]
Hi!

I suggest you take a look at this mod:
https://modrinth.com/mod/foodeffecttooltips

It might be exactly what you are looking for :)

**Comment by Neohedron512** [comment]
Ah! I made the mistake of assuming based on the code from the mod that it wouldn't be compatible with Food Overhaul. The mod appears to work flawlessly thus far with Food Overhaul
